"""Add BillingSetting model

Revision ID: 4f863f74138b
Revises: a702baaf3e7b
Create Date: 2025-10-15 06:41:43.259620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f863f74138b'
down_revision = 'a702baaf3e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixed_charge', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rate_per_unit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_settings')
    # ### end Alembic commands ###
