"""Reading adjustment

Revision ID: b27613f34092
Revises: 4f863f74138b
Create Date: 2025-10-15 14:24:31.291802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27613f34092'
down_revision = '4f863f74138b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_reading', sa.Numeric(precision=12, scale=3), nullable=True))
        batch_op.add_column(sa.Column('total_reading', sa.Numeric(precision=12, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('total_reading')
        batch_op.drop_column('previous_reading')

    # ### end Alembic commands ###
